# If we list all the natural numbers 10 below that are multiples of 3 or 5 , we get 3,5,6 and 9. 
# The sum of these multiples is 23.Find the sum of all the multiples of 3 or 5 below .

# Find the sum of all the multiples 3 of 5:

# i=0
# n=1000
# sum=0
# while i<n:
#     if i%3==0 or i%5==0:
#         sum=sum+i
#     i=i+1
# print(sum)


# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
#  and 
# , the first 
#  terms will be:
                    #  1,2,3,5,8,13,21...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


x=0
y=1
z=1
m=10
sum=0
while z<m:
#    print(z)
   x=y
   y=z
   z=x+y
   if z%2==0:
      sum=sum+z
print(sum)
